#include "sketch/pinc_symbol_counterparts.hpp"

namespace sketch {

std::vector<PincSymbolCounterpart> default_pinc_symbol_counterparts() {
    static const std::vector<PincSymbolCounterpart> counterparts{
        {"Arrow - North", "svg-v2-25_drafting_symbols-north-arrow",
         "Close named graphic match; orientation, artwork, and editing parity are unverified."},
        {"Arrow - Plain", "svg-v2-25_drafting_symbols-arrow-plain",
         "Independent plain-arrow artwork with a nominal editable footprint; it is not a certified product."},
        {"Bath - Bathtub 5'", "svg-v2-01_bathroom-tub-alcove-5ft",
         "Five-foot alcove tub candidate; exact installation and fixture details may differ."},
        {"Bath - Bidet", "svg-v2-01_bathroom-bidet",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Bath - Corner Tub", "svg-v2-01_bathroom-tub-corner",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Bath - Freestanding Tub", "svg-v2-01_bathroom-tub-freestanding-oval",
         "Oval freestanding form selected; Pinc does not specify the tub shape."},
        {"Bath - Linen Cabinet", "svg-v2-08_storage-linen-cabinet",
         "Independent candidate with a nominal editable footprint; exact cabinet details may differ."},
        {"Bath - Pedestal Sink", "svg-v2-01_bathroom-basin-pedestal",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Bath - Shower Corner", "svg-v2-01_bathroom-shower-quadrant",
         "Related quadrant enclosure form; exact Pinc footprint and glass details are unverified."},
        {"Bath - Shower Glass", "svg-v2-01_bathroom-shower-glass",
         "Independent glass-screen artwork with a nominal editable footprint; product details are unverified."},
        {"Bath - Shower Rect", "svg-v2-01_bathroom-shower-rectangular",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Bath - Toilet", "svg-v2-01_bathroom-toilet-close-coupled",
         "Close-coupled tank style may differ from Pinc's generic toilet artwork."},
        {"Bath - Tub / Shower", "svg-v2-01_bathroom-tub-shower-combination",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Bath - Vanity Double", "svg-v2-01_bathroom-vanity-double",
         "Close named match; basin details and source dimensions are unverified."},
        {"Bath - Vanity Single", "svg-v2-01_bathroom-vanity-600",
         "600 mm vanity selected; source width and basin details may differ."},
        {"Cased Opening", "svg-v2-16_walls_openings-opening",
         "Generic opening graphic; casing detail is not named and the asset does not cut a host wall."},
        {"Closet - Rod Shelf", "svg-v2-08_storage-closet-rod-shelf",
         "Independent candidate with a nominal editable footprint; exact closet layout may differ."},
        {"Closet - Walk In", "svg-v2-08_storage-closet-walk-in",
         "Independent walk-in closet candidate with a nominal editable footprint; layout may differ."},
        {"Column", "svg-v2-15_structure_access-column-round",
         "Round form selected; Pinc's unspecified column geometry may instead be square."},
        {"Door - Barn", "svg-v2-09_doors-door-barn",
         "Close type match; hosted operation and artwork parity are unverified."},
        {"Door - Bifold", "svg-v2-09_doors-door-bifold",
         "Close type match; hosted operation and artwork parity are unverified."},
        {"Door - Exterior", "svg-v2-09_doors-door-hinged-810-left",
         "Generic 810 mm left-hinged glyph; source swing, width, and exterior classification are not encoded."},
        {"Door - French Double", "svg-v2-09_doors-door-double",
         "Double-leaf candidate; French glazing and stile details are not confirmed."},
        {"Door - Garage Double", "svg-v2-09_doors-door-garage",
         "Generic garage-door artwork does not distinguish double width; retain the source dimensions."},
        {"Door - Garage Single", "svg-v2-09_doors-door-garage",
         "Same generic garage-door artwork as the double variant; retain the source width and dimensions."},
        {"Door - Interior", "svg-v2-09_doors-door-hinged-810-left",
         "Generic 810 mm left-hinged glyph; source swing, width, and interior classification are not encoded."},
        {"Door - Pocket", "svg-v2-09_doors-door-pocket",
         "Close type match; hosted operation and artwork parity are unverified."},
        {"Door - Sliding", "svg-v2-09_doors-door-sliding-glass",
         "Glass slider candidate; Pinc's generic sliding-door style may differ."},
        {"Fireplace - Corner", "svg-v2-18_fireplace-fireplace-corner",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Fireplace - Double Sided", "svg-v2-18_fireplace-fireplace-double-sided",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Fireplace - Standard", "svg-v2-18_fireplace-fireplace-standard",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Hot Tub", "svg-v2-13_outdoor-hot-tub",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Kitchen - Cabinet Run", "svg-v2-02_kitchen-cabinet-run",
         "Independent cabinet-run candidate with a nominal editable footprint; cabinet layout may differ."},
        {"Kitchen - Cooktop", "svg-v2-02_kitchen-cooktop-gas-four",
         "Four-burner gas form selected; Pinc's name leaves cooktop type and burner count unspecified."},
        {"Kitchen - Corner Cabinet", "svg-v2-02_kitchen-corner-cabinet",
         "Independent candidate with a nominal editable footprint; exact cabinet layout may differ."},
        {"Kitchen - Dishwasher", "svg-v2-02_kitchen-dishwasher",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Kitchen - Island", "svg-v2-02_kitchen-kitchen-island",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Kitchen - Island Seating", "svg-v2-02_kitchen-kitchen-island-seating",
         "Close named match; exact seating and source dimensions are unverified."},
        {"Kitchen - Microwave", "svg-v2-02_kitchen-microwave",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Kitchen - Pantry", "svg-v2-02_kitchen-pantry-cabinet",
         "Independent pantry candidate with a nominal editable footprint; cabinet layout may differ."},
        {"Kitchen - Peninsula", "svg-v2-02_kitchen-kitchen-peninsula",
         "Independent candidate with a nominal editable footprint; exact layout may differ."},
        {"Kitchen - Range", "svg-v2-02_kitchen-range-standard",
         "Standard-width range selected; Pinc's actual range width may differ."},
        {"Kitchen - Refrigerator", "svg-v2-02_kitchen-fridge-french-door",
         "French-door form selected; Pinc's refrigerator configuration is unspecified."},
        {"Kitchen - Sink Base", "svg-v2-02_kitchen-sink-base",
         "Independent sink-base candidate with a nominal editable footprint; basin details may differ."},
        {"Kitchen - Sink Double", "svg-v2-02_kitchen-sink-stainless-double",
         "Double stainless bowl candidate; material and faucet details may differ."},
        {"Kitchen - Sink Single", "svg-v2-02_kitchen-sink-stainless-single",
         "Single stainless bowl selected; Pinc's basin configuration and material are unspecified."},
        {"Kitchen - Wall Oven", "svg-v2-02_kitchen-oven-built-in",
         "Built-in oven candidate; exact wall-oven graphic parity is unverified."},
        {"Laundry - Dryer", "svg-v2-03_laundry_utility-dryer-front-load",
         "Front-load dryer candidate; Pinc does not specify loading style."},
        {"Laundry - Utility Sink", "svg-v2-03_laundry_utility-laundry-sink",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Laundry - Washer", "svg-v2-03_laundry_utility-washer-front-load",
         "Front-load washer selected; Pinc's loading style is unspecified."},
        {"Laundry - Washer Dryer Stack", "svg-v2-03_laundry_utility-washer-dryer-stack",
         "Independent stacked-unit candidate with a nominal editable footprint; product details may differ."},
        {"Mechanical - Electrical Panel", "svg-v2-03_laundry_utility-electrical-panel",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Mechanical - FWA", "svg-v2-03_laundry_utility-air-handler",
         "Related air-handler candidate; forced-warm-air system identity is not confirmed."},
        {"Mechanical - Floor Drain", "svg-v2-20_hvac_plumbing-floor-drain",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Mechanical - Furnace", "svg-v2-20_hvac_plumbing-furnace",
         "Independent furnace candidate with a nominal editable footprint; exact product details may differ."},
        {"Mechanical - HVAC", "svg-v2-20_hvac_plumbing-hvac-system",
         "Independent HVAC-system candidate with a nominal editable footprint; system layout may differ."},
        {"Mechanical - HWB", "svg-v2-20_hvac_plumbing-baseboard-heater",
         "Baseboard-heater candidate; HWB classification and source dimensions are not confirmed by the glyph."},
        {"Mechanical - Sump", "svg-v2-20_hvac_plumbing-sump-pump",
         "Close named equipment match; exact artwork and source dimensions are unverified."},
        {"Mechanical - Water Heater", "svg-v2-03_laundry_utility-water-heater",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Misc - Structural Issue", "svg-v2-25_drafting_symbols-structural-issue",
         "Drawing annotation only; it does not author a model void or establish an engineering issue."},
        {"Open Below", "svg-v2-16_walls_openings-open-below",
         "Drawing annotation only; it does not create or validate a model void."},
        {"Outdoor - Fire Pit", "svg-v2-13_outdoor-fire-pit",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Outdoor - Grill", "svg-v2-13_outdoor-barbecue-grill",
         "Close named match; exact artwork and source dimensions are unverified."},
        {"Pool - Freeform", "svg-v2-21_swimming_pools-pool-freeform",
         "Close named form match; exact outline and source dimensions are unverified."},
        {"Pool - Kidney", "svg-v2-21_swimming_pools-pool-kidney",
         "Independent kidney-shape candidate with a nominal editable footprint; pool product details may differ."},
        {"Pool - Oval", "svg-v2-21_swimming_pools-pool-oval",
         "Close named form match; exact outline and source dimensions are unverified."},
        {"Pool - Rectangle", "svg-v2-21_swimming_pools-pool-rectangular",
         "Close named form match; exact outline and source dimensions are unverified."},
        {"Railing", "svg-v2-17_railings-railing",
         "Named railing graphic selected; exact plan view, attachment, and placement behavior are unverified."},
        {"Stairs Down", "svg-v2-11_circulation-stairs-straight-down",
         "Independent down-stair graphic with a nominal editable footprint; runtime direction semantics are unverified."},
        {"Stairs L", "svg-v2-11_circulation-stairs-l",
         "Close named form match; exact footprint and direction semantics are unverified."},
        {"Stairs Spiral", "svg-v2-11_circulation-stairs-spiral",
         "Close named form match; exact footprint and direction semantics are unverified."},
        {"Stairs U", "svg-v2-11_circulation-stairs-u",
         "Close named form match; exact footprint and direction semantics are unverified."},
        {"Stairs Up", "svg-v2-11_circulation-stairs-straight-up",
         "Independent up-stair graphic with a nominal editable footprint; runtime direction semantics are unverified."},
        {"Window - Bay", "svg-v2-10_windows-window-bay",
         "Bay form retained as its own graphic; hosted wall-opening behavior is unverified."},
        {"Window - Bow", "svg-v2-10_windows-window-bow",
         "Original curved multi-panel bow form; 2.4 by 0.6 m is an editable suggested default, not a certified product."},
        {"Window - Corner", "svg-v2-10_windows-window-corner",
         "Original L-shaped corner form; 1.2 by 1.2 m is an editable suggested default, not a certified product."},
        {"Window - Double", "svg-v2-10_windows-window-double",
         "Close named match; glazing details and hosted wall-opening behavior are unverified."},
        {"Window - Standard", "svg-v2-10_windows-window-standard",
         "Original straight single-lite form; 1.2 by 0.2 m is an editable suggested default, not a certified product."},
        {"Window - Triple", "svg-v2-10_windows-window-triple",
         "Close named match; glazing details and hosted wall-opening behavior are unverified."},
        {"Wood Stove", "svg-v2-18_fireplace-wood-stove",
         "Close named match; exact artwork and source dimensions are unverified."},
    };
    return counterparts;
}

} // namespace sketch
