"""Generate deterministic built-in metadata from the preserved user SVG archive.

Run after importing the raw archive under assets/symbols/architectural_v2.
--check verifies the checked-in output without modifying it. No dependencies.
"""
import argparse
import json
import math
from pathlib import Path, PurePosixPath
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets/symbols/architectural_v2"


def generate(directory):
    index = json.loads((directory / "index.json").read_text(encoding="utf-8"))
    rows = index["symbols"]
    if len(rows) != index["count"] or len(rows) != 320:
        raise ValueError("Expected the complete 320-symbol archive")
    ids, paths = set(), set()
    result = ["// Generated by scripts/generate_architectural_svg_catalog.py; do not edit."]
    for row in sorted(rows, key=lambda r: (r["category"], r["id"])):
        if not all(re.fullmatch(r"[a-z0-9_-]+", row[k]) for k in ("category", "id")):
            raise ValueError("Invalid category or ID")
        identity = "svg-v2-" + row["category"] + "-" + row["id"]
        path = PurePosixPath(row["file"])
        if (identity in ids or str(path) in paths or path.is_absolute() or
                ".." in path.parts or "\\" in row["file"] or
                str(path) != f"symbols/{row['category']}/{row['id']}.svg"):
            raise ValueError("Unsafe or duplicate asset identity/path")
        ids.add(identity)
        paths.add(str(path))
        svg = ET.fromstring((directory / path).read_bytes())
        if svg.tag != "{http://www.w3.org/2000/svg}svg":
            raise ValueError("Not an SVG document")
        box = [float(v) for v in svg.attrib["viewBox"].split()]
        if len(box) != 4 or not all(math.isfinite(v) for v in box) or min(box[2:]) <= 0:
            raise ValueError("Invalid viewBox")
        desc = svg.find("{http://www.w3.org/2000/svg}desc")
        nominal = re.search(r"Nominal footprint (\d+) by (\d+) millimetres",
                            desc.text or "" if desc is not None else "")
        if nominal:
            w, d = map(float, nominal.groups())
            footprint = [0., 0., w, d]
            width, depth = w / 1000, d / 1000
        else:
            footprint = box
            width, depth = box[2] / max(box[2:]), box[3] / max(box[2:])
        quote = lambda s: json.dumps(s, ensure_ascii=True)
        numbers = lambda values: "{" + ", ".join(format(v, ".12g") for v in values) + "}"
        result.append("    {" + ", ".join([
            quote(identity), quote(row["name"]), quote(row["category"]),
            quote(row["id"]), quote("symbols/architectural_v2/" + str(path)),
            format(width, ".12g"), format(depth, ".12g"), numbers(box),
            numbers(footprint), "true" if nominal else "false"]) + "},")
    actual_paths = {p.relative_to(directory).as_posix() for p in (directory / "symbols").rglob("*.svg")}
    if paths != actual_paths:
        raise ValueError("Index and SVG assets do not match")
    return "\n".join(result) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = ASSETS / "catalog_data.inc"
    content = generate(ASSETS)
    if args.check:
        if output.read_text(encoding="utf-8") != content:
            raise SystemExit("SVG catalog metadata is stale; run the generator")
        print("Validated 320 SVG assets and deterministic catalog metadata")
    else:
        output.write_text(content, encoding="utf-8", newline="\n")
